version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - '8000:8000'
    volumes:
      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1
  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    ports:
      - '8501:8501'
    depends_on:
      - api
    volumes:
      - ./:/app
