version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: bd2-api
    ports:
      - '8000:8000'
    volumes:
      - ./storage:/app/storage # Persist storage data
      - ./data:/app/data # Share dataset
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/health']
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 60s

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    container_name: bd2-ui
    ports:
      - '8501:8501'
    depends_on:
      api:
        condition: service_healthy
    volumes:
      - ./storage:/app/storage # Share storage with API
      - ./data:/app/data # Share dataset
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
